### ISSUE TITLE
Python 3 roadmap

### ISSUE THREAD

**Issue by GenevieveBuckley** [DeMarcoLab/3DCT#1]
- [ ] 2to3 automated code conversion of .py files
- [ ] Upgrade to pyqt version 5 (pyqt4 is not supported on python 3)
- [ ] (Optionally?) Regenerate .py files from .ui files with QtDesigner
- [ ] Check & update the tests

**Comment by GenevieveBuckley** [comment]
Some steps towards this taken in https://github.com/GenevieveBuckley/3DCT/tree/python3
